### ISSUE TITLE
Add docs on configuring underlying secret cache

### ISSUE THREAD

**Issue by saikatak** [aws/aws-secretsmanager-jdbc#168]
Currently when using these wrapper drivers implemented by this project there is no notes on how the Driver can be instantiated with custom cache manager having a ttl value configured by the user. 

Would request to add notes on the same. In case if such instantiation is not supported. Can we add the support for the same

**Comment by simonmarty** [comment]
This is already possible through [this constructor](https://github.com/aws/aws-secretsmanager-jdbc/blob/v2/src/main/java/com/amazonaws/secretsmanager/sql/AWSSecretsManagerDriver.java#L164-L172).

**Comment by simonmarty** [comment]
There are already docs on this [here](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_jdbc.html)
---------
To configure the cache, see [SecretCacheConfiguration](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_cache-java-ref_SecretCacheConfiguration.html).

**Comment by mbucc** [comment]
@simonmarty

How do I configure the cache when using a connection pool such as the c3p0 examples provided in the README?

I'm asking on this ticket because this is where Google sent when trying to figure this out.

Issue https://github.com/aws/aws-secretsmanager-jdbc/discussions/214 suggests that the sample pool configuration given in the README does not enable the cache.  That jibes with my reading of the code, as I didn't see anything related to caching in [`JDBCSecretCacheBuilderProvider`](https://github.com/aws/aws-secretsmanager-jdbc/blob/v2/src/main/java/com/amazonaws/secretsmanager/util/JDBCSecretCacheBuilderProvider.java#L46-L56).

While https://github.com/aws/aws-secretsmanager-jdbc/discussions/214 is discussing Hikari, https://github.com/aws/aws-secretsmanager-jdbc/issues/13#issuecomment-749447785 shows that the Hikari pool works fine with this AWS library (as expected).  If you could provide an example of how I should configure the cache when using a connection pool, that would be much appreciated.

Is it only possible to do programmatically?
