### ISSUE TITLE
Allows change cache item ttl from the outside

### ISSUE THREAD

**Issue by kuraun** [aws/aws-secretsmanager-jdbc#56]
I'm trying to create a data source using an application config file like Spring Boot. However, the current implementation does not allow you to change the `SecretCacheConfiguration.cacheItemTTL` externally.
Therefore, I propose a method to specify `SecretCacheConfiguration.cacheItemTTL` from outside the program with system properties or environment variables.

**Comment by kuraun** [comment]
I decided to create my own library. Thank you

**Comment by harpreet86** [comment]
I also need such configuration. I am using Dropwizard framework which uses JDBI 3 and I can pass driver name via configuration but it instantiates the AWSSecretsManagerPostgreSQLDriver with default value(1 hour) for cacheItemTTL but I want to pass this via configuration instead of writing a lot of boilerplate code just to configure this value. 

Please fix this or suggest if this is already fixed/available.
